# -*- coding: utf-8 -*-
from . import project_task
from . import stock_lot
from . import installation_checklist
from . import installation_checklist_item
from . import mail_message
from . import service_checklist
from . import service_checklist_item
from . import res_users
from . import task_worksheet
from . import worksheet_attendance
from . import team_member_question
from . import team_member
from . import wrokseet_member_question
from . import product_template
from . import worksheet_history
from . import worksheet_notification
from . import electrical_contract_license
from . import work_type
from . import license_tags
from . import documents_document
from . import swms_risk_register
from . import swms_risk_work
from . import swms_team_member_input
