# -*- coding: utf-8 -*-
{
    'name': 'Beyond Worksheet',
    'category': 'Project',
    'version': '17.0.1.0.0',
    'author': """""",
    'website': """""",
    'summary': '',
    'description': """""",
    'depends': ['base', 'project', 'web', 'sale_project', 'project_beyond_solar', 'hr','portal'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'data/hr_department_data.xml',
        'views/project_task_view.xml',
        'views/stock_lot_view.xml',
        'views/task_worksheet_views.xml',
        'views/team_member_question_views.xml',
        'views/installation_checklist_view.xml',
        'views/installation_checklist_item_view.xml',
        'views/mail_message_view.xml',
        'views/owner_signature_templates.xml',
        'views/worksheet_members_templates.xml',
        'views/team_member_question_template.xml',
        'views/service_checklist_view.xml',
        'views/service_checklist_item_view.xml',
        'views/res_users_view.xml',
        'views/worksheet_weekly_mail.xml',
        'views/worksheet_attendance_view.xml',
        'views/product_template_views.xml',
        'views/worksheet_history_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
           'beyond_worksheet/static/src/widgets/checklist_widget.js',
            'beyond_worksheet/static/src/widgets/checklist_widget.xml'
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'OPL-1',
}
