# -*- coding: utf-8 -*-
{
    'name': 'Beyond Worksheet',
    'category': 'Project',
    'version': '17.0.1.0.0',
    'author': """""",
    'website': """""",
    'summary': '',
    'description': """""",
    'depends': ['base', 'project', 'web', 'sale_project', 'project_beyond_solar', 'hr', 'portal', 'documents_project', 'survey'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'data/hr_department_data.xml',
        'data/work_type_data.xml',
        'data/license_tags_data.xml',
        'data/documents_document_data.xml',
        'data/swms_risk_work_data.xml',
        'views/project_task_views.xml',
        'views/stock_lot_views.xml',
        'views/task_worksheet_views.xml',
        'views/team_member_question_views.xml',
        'views/team_member_views.xml',
        'views/installation_checklist_views.xml',
        'views/installation_checklist_item_views.xml',
        'views/mail_message_views.xml',
        'views/owner_signature_templates.xml',
        'views/worksheet_members_templates.xml',
        'views/team_member_question_templates.xml',
        'views/service_checklist_views.xml',
        'views/service_checklist_item_views.xml',
        'views/res_users_views.xml',
        'views/worksheet_weekly_mail.xml',
        'views/worksheet_attendance_views.xml',
        'views/product_template_views.xml',
        'views/worksheet_history_views.xml',
        'views/worksheet_notification_views.xml',
        'views/work_type_views.xml',
        'views/license_tags_views.xml',
        'views/documents_document_views.xml',
        'views/swms_risk_register_views.xml',
        'views/swms_risk_work_views.xml',
        'views/swms_team_member_input_views.xml',
        'views/swms_report_views.xml',
        'report/swms_pdf_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'beyond_worksheet/static/src/widgets/overview_widget.css',
            'beyond_worksheet/static/src/widgets/checklist_widget.js',
            'beyond_worksheet/static/src/widgets/overview_widget.js',
            'beyond_worksheet/static/src/popups/update_checklist_overview_popups/update_checklist_overview_popups.js',
            'beyond_worksheet/static/src/popups/checklist_overview_popups/checklist_overview_popup.js',
            'beyond_worksheet/static/src/widgets/checklist_widget.xml',
            'beyond_worksheet/static/src/widgets/overview_widget.xml',
            'beyond_worksheet/static/src/views/documents_inspector.xml',
            'beyond_worksheet/static/src/popups/update_checklist_overview_popups/update_checklist_overview_popups.xml',
            'beyond_worksheet/static/src/popups/checklist_overview_popups/checklist_overview_popup.xml',
            'beyond_worksheet/static/src/popups/checklist_overview_popups/checklist_overview_popup.scss',
            'beyond_worksheet/static/src/widgets/risk_color_widget/risk_color_widget.js',
            'beyond_worksheet/static/src/widgets/risk_color_widget/risk_color_widget.xml',
            # 'beyond_worksheet/static/src/core/beyond_portal_signature.js',

        ],
        'web.assets_frontend': [
            'beyond_worksheet/static/src/js/employee_check_in.js',
            'beyond_worksheet/static/src/js/workheet_member_check_in.js',
            'beyond_worksheet/static/src/core/beyond_portal_signature.xml',
            'beyond_worksheet/static/src/core/signature_forum.js'

        ],
        'survey.survey_assets': [
            'beyond_worksheet/static/src/js/worsheet_member_check_out.js',
        ],
        #     'web._assets_core': [
        #         'beyond_worksheet/static/src/core/beyond_portal_signature.js',
        #         'beyond_worksheet/static/src/core/beyond_portal_signature.xml'
        #
        #     ]
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'OPL-1',
}
